dist: bionic
language: go
env:
  - GO111MODULE=on
go:
  - 1.12.x
git:
  depth: 1
install: true
notifications:
  email: true
before_script:
  - go get golang.org/x/tools/cmd/goimports
script:
  - go imports
  - go vet